# more hooks in https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    args: ['--style=.style.yapf', '--parallel', '--in-place']

- repo: git://github.com/martyngigg/pre-commit-clang-format
  rev: fdf030fe103cfc838b6fe0c7cbd968e75cfa94ba
  hooks:
  - id: clang-format

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.7.0  # Use the ref you want to point at
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

#- repo: https://github.com/cheshirekow/cmake-format-precommit
#  rev: v0.6.10
#  hooks:
#  - id: cmake-lint
#  - id: cmake-format
